name: conan-package

on:
  push:
    paths:
      - 'cura/**'
      - 'uranium/**'
      - 'windows'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/requirements-runner.txt'
      - 'conanfile.py'
      - 'conandata.yml'
    branches:
      - main
      - 'CURA-*'
      - '[0-9].[0-9]*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]'

# FIXME: point to `main` once merged
jobs:
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-10831
    with:
      project_name: cura_binary_data

  conan-package-export:
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
    secrets: inherit

  conan-package-create-windows:
    needs: [ conan-recipe-version, conan-package-export ]

    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-windows.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit

  conan-package-create-linux:
    needs: [ conan-recipe-version, conan-package-export ]

    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-linux.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit