---
name: conan-package

# Exports the recipe, sources and binaries for Mac, Windows and Linux and upload these to the server such that these can
# be used downstream.
#
# It should run on pushes against main or CURA-* branches, but it will only create the binaries for main and release branches

on:
    push:
        paths:
            - 'cura/**'
            - 'uranium/**'
            - 'windows'
            - '.github/workflows/conan-package.yml'
            - 'GitVersion.yml'
        branches:
            - main
            - 'CURA-*'
            - '[0-9]+.[0-9]+'
        tags:
            - '[0-9]+.[0-9]+.[0-9]+'

jobs:
    conan-recipe-version:
        uses: ultimaker/cura/.github/workflows/conan-recipe-version.yml@CURA-9365_fix_building_cura_main
        with:
            project_name: cura_binary_data

    conan-package-export-macos:
        needs: [ conan-recipe-version ]
        uses: ultimaker/cura/.github/workflows/conan-recipe-export.yml@CURA-9365_fix_building_cura_main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
            recipe_id_pr: ${{ needs.conan-recipe-version.outputs.recipe_id_pr }}
            runs_on: 'macos-10.15'
            python_version: '3.10.4'
            conan_config_branch: 'CURA-9177_Fix_CI_CD'
            conan_logging_level: 'info'
            conan_export_binaries: true
        secrets: inherit

    conan-package-export-linux:
        needs: [ conan-recipe-version ]
        uses: ultimaker/cura/.github/workflows/conan-recipe-export.yml@CURA-9365_fix_building_cura_main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
            recipe_id_pr: ${{ needs.conan-recipe-version.outputs.recipe_id_pr }}
            runs_on: 'ubuntu-20.04'
            python_version: '3.10.4'
            conan_config_branch: 'CURA-9177_Fix_CI_CD'
            conan_logging_level: 'info'
            conan_export_binaries: true
        secrets: inherit

    conan-package-export-windows:
        needs: [ conan-recipe-version ]
        uses: ultimaker/cura/.github/workflows/conan-recipe-export.yml@CURA-9365_fix_building_cura_main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
            recipe_id_pr: ${{ needs.conan-recipe-version.outputs.recipe_id_pr }}
            runs_on: 'windows-2022'
            python_version: '3.10.4'
            conan_config_branch: 'CURA-9177_Fix_CI_CD'
            conan_logging_level: 'info'
            conan_export_binaries: true
        secrets: inherit

    notify-export:
        if: ${{ always() }}
        needs: [ conan-package-export-linux, conan-package-export-macos, conan-package-export-windows ]

        uses: ultimaker/cura/.github/workflows/notify.yml@CURA-9365_fix_building_cura_main
        with:
            success: ${{ contains(join(needs.*.result, ','), 'success') }}
            success_title: "New Conan recipe exported in ${{ github.repository }}"
            success_body: "Exported ${{ needs.conan-recipe-version.outputs.recipe_id_full }}"
            failure_title: "Failed to export Conan Export in ${{ github.repository }}"
            failure_body: "Failed to exported ${{ needs.conan-recipe-version.outputs.recipe_id_full }}"
        secrets: inherit
