name: conan-package

on:
  push:
    paths:
      - 'cura/**'
      - 'uranium/**'
      - 'windows/**'
      - '.github/workflows/conan-package.yml'
      - 'conanfile.py'
      - 'conandata.yml'
    branches:
      - main
      - master
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
# FIXME: Use main once merged
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@CURA-11622_conan_v2
    with:
      package_name: cura_binary_data
      platform_mac: false
      install_system_dependencies: false
    secrets: inherit
